### ISSUE TITLE
OIDC setup throws error after oxAuth key rotation

### ISSUE THREAD

**Issue by iromli** [GluuFederation/cluster-mgr#13]
As per conversation with @aliaksander-samuseu:

```
[08.37.41] Alex Samuseu: Hi, Isman
[08.38.05] Alex Samuseu: I tried to configure key rotation after replication was set
[08.39.30] Alex Samuseu: After that my OIDC setup started to throw this error: "Failed to validate at_hash" So it seems it can't validate received id_token anymore. Everything was working before I rotated keys a couple of times
[08.41.12] Alex Samuseu: So, whatever happened, it seems keys oxAuth actually uses to sign/encrypt everything are now different from keys it publishes at /oxauth/seam/resource/restv1/oxauth/jwks
[10.38.16] Isman Firmansyah: hi Alex
[10.38.28] Isman Firmansyah: ok, i will investigate
```

There was issue with OIDC setup after oxAuth key rotation occured.

**Comment by iromli** [comment]
One of my finding is OIDC get confused because missing private key algorithm. Currently, cluster manager re-generate key using RS512 algorithm.

A quick test using all algorithms (RS256 RS384 RS512 ES256 ES384 ES512) removes the error, but with a gotcha: OIDC must be restarted to take effect. Note, I'm using oxd-python to test key rotation stored in `oxauth-keys.jks`.

**Comment by iromli** [comment]
For JKS backend, I can use oxauth-client JAR to generate keys for each supported algorithms using a single command.

For oxEleven backend, I can't use oxauth-client JAR as it throws the following error:

```
» java -jar keygen.jar -algorithms RS256 RS384 RS512 ES256 ES384 ES512 -expiration 365 -dnname 'CN=oxAuth CA Certificates' -ox11 http://localhost:8080/oxeleven/rest/oxeleven/generateKey -at secret
%d [%thread] %-5level %logger - %msg%n java.lang.IllegalStateException: Target host is null
        at org.apache.http.util.Asserts.notNull(Asserts.java:52) ~[keygen.jar:?]
        at org.apache.http.impl.conn.DefaultHttpRoutePlanner.determineRoute(DefaultHttpRoutePlanner.java:100) ~[keygen.jar:?]
        at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:761) ~[keygen.jar:?]
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:380) ~[keygen.jar:?]
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[keygen.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[keygen.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[keygen.jar:?]
        at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.execute(ApacheHttpClient4Executor.java:195) ~[keygen.jar:?]
        at org.jboss.resteasy.client.ClientRequest.execute(ClientRequest.java:439) ~[keygen.jar:?]
        at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:686) ~[keygen.jar:?]
        at org.jboss.resteasy.client.ClientRequest.post(ClientRequest.java:570) ~[keygen.jar:?]
        at org.jboss.resteasy.client.ClientRequest.post(ClientRequest.java:575) ~[keygen.jar:?]
        at org.gluu.oxeleven.client.GenerateKeyClient.exec(GenerateKeyClient.java:78) ~[keygen.jar:?]
        at org.xdi.oxauth.model.crypto.OxElevenCryptoProvider.generateKey(OxElevenCryptoProvider.java:45) ~[keygen.jar:?]
        at org.xdi.oxauth.util.KeyGenerator$Cli.parse(KeyGenerator.java:121) [keygen.jar:?]
        at org.xdi.oxauth.util.KeyGenerator.main(KeyGenerator.java:65) [keygen.jar:?]
usage: KeyGenerator -algorithms alg ... -expiration n_days [-ox11 url]
                    [-keystore path -keypasswd secret -dnname dn_name]
 -algorithms <arg>   Signature Algorithms (RS256 RS384 RS512 ES256 ES384
                     ES512).
 -at <arg>           oxEleven Access Token
 -dnname <arg>       DN of certificate issuer.
 -expiration <arg>   Expiration in days.
 -h                  Show help.
 -keypasswd <arg>    Key Store password.
 -keystore <arg>     Key Store file.
 -ox11 <arg>         oxEleven Generate Key Endpoint.
```

@qbert2k any idea where to look at for troubleshooting?

**Comment by iromli** [comment]
Ended up with making request to oxEleven API for each algorithm. Patch is merged to `master` branch.

**Comment by iromli** [comment]
Arrived in latest `python-cluster-mgr` debian package.
