### ISSUE TITLE
Trying To Removed Stopped Gluu Server From Cluster Throws Error

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#209]
As follows:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr-3.1.3.post6-py2.7.egg/clustermgr/application.py", line 25, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr-3.1.3.post6-py2.7.egg/clustermgr/tasks/cluster.py", line 1513, in remove_server_from_cluster
    csync2_config = get_csync2_config(exclude=removed_server_hostname)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr-3.1.3.post6-py2.7.egg/clustermgr/tasks/cluster.py", line 161, in get_csync2_config
    for l in open(replication_user_file).readlines():
IOError: [Errno 2] No such file or directory: '/root/.clustermgr/fs_replication_paths.txt'
```

`fs_replication_paths.txt` doesn't exist on the cluster manager machine.

**Comment by afroDC** [comment]
![image](https://user-images.githubusercontent.com/30447907/42334474-ebd5dd86-8042-11e8-9331-4cb050ea98e9.png)

It seems to also be attempting to restart stunnel with a `systemctl` command instead of a `service stunnel4 restart` command on Ubuntu 16.
