### ISSUE TITLE
Unable to Gather Monitoring Data

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#210]
I'm getting the following log from `~/.clustermgr/celery.log` throwing a few errors:

```
[2018-07-13 17:25:20,617: WARNING/ForkPoolWorker-1] Monitoring: getting data for server c5.gluu.org
[2018-07-13 17:25:20,618: ERROR/ForkPoolWorker-1] Task clustermgr.tasks.get_remote_stats.get_remote_stats[4dad3b25-1f6c-4c47-9442-c80a889d8040] raised unexpected: IOError(24, 'Too many open files')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/application.py", line 25, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/tasks/get_remote_stats.py", line 139, in get_remote_stats
    c = RemoteClient(server.hostname, ip=server.ip)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/core/remote.py", line 55, in __init__
    encoded_passphrase = open(pw_file).read()
IOError: [Errno 24] Too many open files: '/root/.clustermgr/.pw'
[2018-07-13 17:30:20,708: WARNING/ForkPoolWorker-1] Monitoring: getting data for server c5.gluu.org
[2018-07-13 17:30:20,709: ERROR/ForkPoolWorker-1] Task clustermgr.tasks.get_remote_stats.get_remote_stats[86431e33-d144-4fc3-828a-2b9f88ead2b7] raised unexpected: IOError(24, 'Too many open files')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/application.py", line 25, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/tasks/get_remote_stats.py", line 139, in get_remote_stats
    c = RemoteClient(server.hostname, ip=server.ip)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/core/remote.py", line 55, in __init__
    encoded_passphrase = open(pw_file).read()
IOError: [Errno 24] Too many open files: '/root/.clustermgr/.pw'
[2018-07-13 17:34:38,693: WARNING/ForkPoolWorker-1] Monitoring: getting data for server c5.gluu.org
[2018-07-13 17:34:38,782: ERROR/ForkPoolWorker-1] Task clustermgr.tasks.get_remote_stats.get_remote_stats[3b0e1a99-19db-4285-8219-3e1064b4309f] raised unexpected: KeyError('e',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/application.py", line 25, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/tasks/get_remote_stats.py", line 146, in get_remote_stats
    print "Monitoring: An error occurred while retreiveing monitoring data from server {}. Error {e}".format(server.hostname, e)
KeyError: 'e'
```

I'm getting 0 logging information for `System Monitoring`:

```
Data column(s) for axis #0 cannot be of type string.
```

Note I previously stopped InfluxDB on the Cluster Manager server to deal with a port conflict. I've since restarted it.

**Comment by afroDC** [comment]
Restarting Cluster Manager and reinitiating my browser session seemed to fix the issue. I think it had to do with needing to establish the key password again. I am receiving monitoring data as expected.

**Comment by mbaser** [comment]
The issue seems here:
`IOError: [Errno 24] Too many open files: '/root/.clustermgr/.pw'`
I don't know why it opens .pw file that much

**Comment by mbaser** [comment]
commit 104689974dac36547c2810a54bc6fc4d0f12fe7f should solve this issue, needs to be tested.

**Comment by mbaser** [comment]
commit 1046899 closed this issue
