### ISSUE TITLE
CM setting ldapURL in ldap.properties to hostname instead of localhost

### ISSUE THREAD

**Issue by mogluu** [GluuFederation/cluster-mgr#255]
In the `/opt/shibboleth-idp/conf/ldap.properties`

After initial setup it will show that all services are running however there is an issue in the ldap.properties files which causes the idp service to not start .

```
## Connection properties ##
idp.authn.LDAP.ldapURL                          = ldaps://demo-gluu-server-.com:1636 ldaps://demo-gluu-server-2.com:1636
idp.authn.LDAP.useStartTLS                      = false
idp.authn.LDAP.useSSL                           = true
```
Right config is as following:

```
## Connection properties ##
idp.authn.LDAP.ldapURL                          = ldaps://localhost:1636
```

**Comment by mbaser** [comment]
The idea for including multiple ldap address is that if one ldap fails, it will try other. I will work on this why it dislikes multpile ldap addresses. It was working previously.

**Comment by justinfiore** [comment]
@mbaser This is the exception we were getting on startup:
```
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Hostname '[demo-gluu-server-1.usw2.demo.inmoment.com, demo-gluu-server-2.usw2.demo.inmoment.com]' does not match the hostname in the server's certificate 'CN=localhost, O=OpenDJ RSA Self-Signed Certificate'
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
Caused by: java.security.cert.CertificateException: Hostname '[demo-gluu-server-1.usw2.demo.inmoment.com, demo-gluu-server-2.usw2.demo.inmoment.com]' does not match the hostname in the server's certificate 'CN=localhost, O=OpenDJ RSA Self-Signed Certificate'
        at org.ldaptive.ssl.HostnameVerifyingTrustManager.checkCertificateTrusted(HostnameVerifyingTrustManager.java:100)
2019-03-28 15:28:57,492 - WARN [net.shibboleth.ext.spring.context.FilesystemGenericApplicationContext:551] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteLDAP': Invocation of init method failed; nested exception is net.shibboleth.utilities.java.support.component.ComponentInitializationException: Data Connector 'siteLDAP': Invalid connector configuration
2019-03-28 15:28:57,499 - ERROR [net.shibboleth.utilities.java.support.service.AbstractReloadableService:181] - Service 'shibboleth.AttributeResolverService': Initial load failed
net.shibboleth.utilities.java.support.service.ServiceException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteLDAP': Invocation of init method failed; nested exception is net.shibboleth.utilities.java.support.component.ComponentInitializationException: Data Connector 'siteLDAP': Invalid connector configuration
        at net.shibboleth.ext.spring.service.ReloadableSpringService.doReload(ReloadableSpringService.java:336)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteLDAP': Invocation of init method failed; nested exception is net.shibboleth.utilities.java.support.component.ComponentInitializationException: Data Connector 'siteLDAP': Invalid connector configuration
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
Caused by: net.shibboleth.utilities.java.support.component.ComponentInitializationException: Data Connector 'siteLDAP': Invalid connector configuration
        at net.shibboleth.idp.attribute.resolver.dc.ldap.impl.LDAPDataConnector.doInitialize(LDAPDataConnector.java:151)
Caused by: net.shibboleth.idp.attribute.resolver.dc.ValidationException: [org.ldaptive.provider.ConnectionException@262535196::resultCode=PROTOCOL_ERROR, matchedDn=null, responseControls=null, referralURLs=null, messageId=-1, message=javax.naming.CommunicationException: demo-gluu-server-2.usw2.demo.inmoment.com:1636 [Root exception is javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Hostname '[demo-gluu-server-1.usw2.demo.inmoment.com, demo-gluu-server-2.usw2.demo.inmoment.com]' does not match the hostname in the server's certificate 'CN=localhost, O=OpenDJ RSA Self-Signed Certificate'], providerException=javax.naming.CommunicationException: demo-gluu-server-2.usw2.demo.inmoment.com:1636 [Root exception is javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Hostname '[demo-gluu-server-1.usw2.demo.inmoment.com, demo-gluu-server-2.usw2.demo.inmoment.com]' does not match the hostname in the server's certificate 'CN=localhost, O=OpenDJ RSA Self-Signed Certificate']]
        at net.shibboleth.idp.attribute.resolver.dc.ldap.impl.ConnectionFactoryValidator.validate(ConnectionFactoryValidator.java:154)
Caused by: org.ldaptive.provider.ConnectionException: javax.naming.CommunicationException: demo-gluu-server-2.usw2.demo.inmoment.com:1636 [Root exception is javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Hostname '[demo-gluu-server-1.usw2.demo.inmoment.com, demo-gluu-server-2.usw2.demo.inmoment.com]' does not match the hostname in the server's certificate 'CN=localhost, O=OpenDJ RSA Self-Signed Certificate']
        at org.ldaptive.provider.jndi.JndiConnectionFactory.createInternal(JndiConnectionFactory.java:102)
Caused by: javax.naming.CommunicationException: demo-gluu-server-2.usw2.demo.inmoment.com:1636
        at com.sun.jndi.ldap.Connection.<init>(Connection.java:238)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Hostname '[demo-gluu-server-1.usw2.demo.inmoment.com, demo-gluu-server-2.usw2.demo.inmoment.com]' does not match the hostname in the server's certificate 'CN=localhost, O=OpenDJ RSA Self-Signed Certificate'
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
Caused by: java.security.cert.CertificateException: Hostname '[demo-gluu-server-1.usw2.demo.inmoment.com, demo-gluu-server-2.usw2.demo.inmoment.com]' does not match the hostname in the server's certificate 'CN=localhost, O=OpenDJ RSA Self-Signed Certificate'
        at org.ldaptive.ssl.HostnameVerifyingTrustManager.checkCertificateTrusted(HostnameVerifyingTrustManager.java:100)
```

**Comment by mbaser** [comment]
commented out this settings in commit 63882363840dd10addbeb3fd963e31729f549783
