### ISSUE TITLE
Cluster-Manager installation failing

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#269]
Installation went okay. Starting 'cluster-mgr' failing. 
CentOS 7, AWS 

```
Starting Celery Worker
celery multi v4.3.0 (rhubarb)
> Starting nodes...
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 20, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 288, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 502, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 524, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/lib/python2.7/site-packages/celery/app/utils.py", line 368, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 527, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/usr/lib/python2.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/bin/clusterapp.py", line 22, in <module>
    app = create_app()
  File "/usr/lib/python2.7/site-packages/clustermgr/application.py", line 45, in create_app
    silent=True,
  File "/usr/lib/python2.7/site-packages/flask/config.py", line 132, in from_pyfile
    exec(compile(config_file.read(), filename, "exec"), d.__dict__)
  File "/root/.clustermgr/instance/config.py", line 1
    DEBUG = False\nSECRET_KEY = 'ES6nZcCHFBzUmNUDt42fA3M21TWuyxgW'\nLICENSE_ENFORCEMENT_ENABLED = True
                                                                                                     ^
SyntaxError: unexpected character after line continuation character
        > worker@ip-172-31-42-239.us-west-2.compute.internal: * Child terminated with exit code 1
FAILED
Starting Celery Beat
Traceback (most recent call last):
  File "/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 288, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 502, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 524, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/lib/python2.7/site-packages/celery/app/utils.py", line 368, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 527, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/usr/lib/python2.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/bin/clusterapp.py", line 22, in <module>
    app = create_app()
  File "/usr/lib/python2.7/site-packages/clustermgr/application.py", line 45, in create_app
    silent=True,
  File "/usr/lib/python2.7/site-packages/flask/config.py", line 132, in from_pyfile
    exec(compile(config_file.read(), filename, "exec"), d.__dict__)
  File "/root/.clustermgr/instance/config.py", line 1
    DEBUG = False\nSECRET_KEY = 'ES6nZcCHFBzUmNUDt42fA3M21TWuyxgW'\nLICENSE_ENFORCEMENT_ENABLED = True
                                                                                                     ^
SyntaxError: unexpected character after line continuation character
Starting Gunicorn Web Server
[root@ip-172-31-42-239 ~]#
```

**Comment by mzico** [comment]
up to 3.1.6-06, it's okay. 

```
Successfully installed clustermgr-3.1.6.post6
You are using pip version 8.1.2, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@myclustermanager ~]# clustermgr-cli stop
Stopping Celery Workers
...
...
...
For more details see kill(1).
[root@myclustermanager ~]# clustermgr-cli start
Upgrading Database
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5246a3f7a7e4, consolidated all server models
INFO  [alembic.runtime.migration] Running upgrade 5246a3f7a7e4 -> fb4b3b50c872, adds nginx_host to appconfig
INFO  [alembic.runtime.migration] Running upgrade fb4b3b50c872 -> d14788040223, added redis and stunnel flags to server
INFO  [alembic.runtime.migration] Running upgrade d14788040223 -> 987b4b9f18bb, add log_purge column to appconfig
INFO  [alembic.runtime.migration] Running upgrade 987b4b9f18bb -> 2a0c96ff52f6, add admin_email field
INFO  [alembic.runtime.migration] Running upgrade 2a0c96ff52f6 -> 2926b8ffa2f0, empty message
INFO  [alembic.runtime.migration] Running upgrade 2926b8ffa2f0 -> 8385d7dcdcdc, add filebeat column
INFO  [alembic.runtime.migration] Running upgrade 8385d7dcdcdc -> 601d70820f5d, add modify_hosts to AppConfiguration
INFO  [alembic.runtime.migration] Running upgrade 601d70820f5d -> 4fca7c65b3df, add nginx_ip column to appconfig
INFO  [alembic.runtime.migration] Running upgrade 4fca7c65b3df -> b21895d83725, add ldap_update_period to AppConfiguration
INFO  [alembic.runtime.migration] Running upgrade b21895d83725 -> 0e7453df1644, update keyrotation
INFO  [alembic.runtime.migration] Running upgrade 0e7453df1644 -> 5cc68648b63e, add monitoring for servers
INFO  [alembic.runtime.migration] Running upgrade 5cc68648b63e -> dd4a741b7bd0, empty message
INFO  [alembic.runtime.migration] Running upgrade dd4a741b7bd0 -> ac40bca26010, empty message
INFO  [alembic.runtime.migration] Running upgrade ac40bca26010 -> 55c791eac900, empty message
INFO  [alembic.runtime.migration] Running upgrade 55c791eac900 -> 0c35f58a2e73, empty message
INFO  [alembic.runtime.migration] Running upgrade 0c35f58a2e73 -> 22f6c85b4b24, empty message
INFO  [alembic.runtime.migration] Running upgrade 22f6c85b4b24 -> ab705f5bfabf, add cache_host and cache_ip
INFO  [alembic.runtime.migration] Running upgrade ab705f5bfabf -> ac044ab840e8, add use_ldap_cache to AppConfiguration
INFO  [alembic.runtime.migration] Running upgrade ac044ab840e8 -> 867fa650eacd, add nginx_os_type
INFO  [alembic.runtime.migration] Running upgrade 867fa650eacd -> 496b3a1cbc65, add ldap_update_period_unit to AppConfiguration
INFO  [alembic.runtime.migration] Running upgrade 496b3a1cbc65 -> 54968b4c309f, add latest_version to AppConfiguration
INFO  [alembic.runtime.migration] Running upgrade 54968b4c309f -> dfb03ed2c00d, add install_redis to AppConfiguration
INFO  [alembic.runtime.migration] Running upgrade dfb03ed2c00d -> edb3a875fde8, add CacheServer model
INFO  [alembic.runtime.migration] Running upgrade edb3a875fde8 -> 6f0d7d321e8b, remove cache_host, cache_ip and install_redis from AppConfiguration
INFO  [alembic.runtime.migration] Running upgrade 6f0d7d321e8b -> 0688ae3baa88, add offline installation fields
Starting Celery Worker
celery multi v4.3.0 (rhubarb)
> Starting nodes...
        > worker@myclustermanager: OK
Starting Celery Beat
Starting Gunicorn Web Server
[root@myclustermanager ~]#

```
