### ISSUE TITLE
Couldn't install redis in CentOS 7 VM

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#298]
Using Cluster Manager ( version: 4.1-3) to install cluster which is primarily CentOS 7 based. 
As usual, Redis machine was CentOS 7 but couldn't install redis there due to below error. 
Had to use Ubuntu 18 machine to continue installation. There is also no indication in doc that... Redis machine has to be Ubuntu/Debian. 

Cluster manager throw below error: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/application.py", line 25, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/tasks/cache.py", line 144, in install_cache_cluster
    logger_task_id=task_id
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/core/clustermgr_installer.py", line 67, in __init__
    self.settings()
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/core/clustermgr_installer.py", line 79, in settings
    if ('Ubuntu' in self.server_os) or ('Debian' in self.server_os):
TypeError: argument of type 'NoneType' is not iterable
```

![redisFailing_installation](https://user-images.githubusercontent.com/7156097/79225700-bcd0a680-7e22-11ea-8aec-a255f7a16de5.PNG)

**Comment by mbaser** [comment]
The error is not related to redis installation. It seems os type were not be able to identified.

**Comment by mbaser** [comment]
Only missing is epel release.
![Screenshot_2020-05-05_15-11-05](https://user-images.githubusercontent.com/6398752/81064674-c5c50d00-8ee2-11ea-85cc-d142387e22a8.png)

**Comment by mbaser** [comment]
epel release is enabled.
