### ISSUE TITLE
Cluster-mgr4 not starting in Ubuntu 18 VM

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#301]
```
root@ip-172-31-32-143:~# clustermgr4-cli start
Upgrading Database
Traceback (most recent call last):
  File "/usr/local/bin/clusterapp.py", line 21, in <module>
    app = create_app()
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/application.py", line 71, in create_app
    from clustermgr.views.index import index
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/views/index.py", line 41, in <module>
    from clustermgr.tasks.server import collect_server_details, set_up_ldap_cache_cleaner
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/tasks/server.py", line 747
    wlogger.log(task_id, "Connecting LDAP Server: {}".format(server.hostname), 'debug')
    ^
IndentationError: unexpected indent
Starting Celery Worker
celery multi v4.2.1 (windowlicker)
> Starting nodes...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 20, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 273, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 501, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 359, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 504, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/bin/clusterapp.py", line 21, in <module>
    app = create_app()
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/application.py", line 71, in create_app
    from clustermgr.views.index import index
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/views/index.py", line 41, in <module>
    from clustermgr.tasks.server import collect_server_details, set_up_ldap_cache_cleaner
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/tasks/server.py", line 747
    wlogger.log(task_id, "Connecting LDAP Server: {}".format(server.hostname), 'debug')
    ^
IndentationError: unexpected indent
        > worker@ip-172-31-32-143: * Child terminated with exit code 1
FAILED
Starting Celery Beat
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 273, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 501, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 359, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 504, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/bin/clusterapp.py", line 21, in <module>
    app = create_app()
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/application.py", line 71, in create_app
    from clustermgr.views.index import index
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/views/index.py", line 41, in <module>
    from clustermgr.tasks.server import collect_server_details, set_up_ldap_cache_cleaner
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/tasks/server.py", line 747
    wlogger.log(task_id, "Connecting LDAP Server: {}".format(server.hostname), 'debug')
    ^
IndentationError: unexpected indent
Starting Gunicorn Web Server
root@ip-172-31-32-143:~#
```

**Comment by mbaser** [comment]
fixed
