### ISSUE TITLE
Unable to add cache server in CM 4.1

### ISSUE THREAD

**Issue by sobhanpanda** [GluuFederation/cluster-mgr#310]
I was testing Gluu Cluster manager 4.1 (in Ubuntu 18) and faced issue while adding cache server.

The error message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/views/cache.py", line 157, in add_cache_server
    return render_template( 'cache_server.html', form=form)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python2.7/dist-packages/clustermgr/templates/cache_server.html", line 31, in top-level template code
    {{ form.ssh_port(class="form-control") }}
TypeError: 'int' object is not callable
```

And the screen appears like:
![image](https://user-images.githubusercontent.com/20181885/89193805-24725380-d5c4-11ea-8a2c-3cc37dbb0b0d.png)

**Comment by mbaser** [comment]
Fixed in commit 88483bd74e0bc21de3c3e0ea861defcf3b2654e2
