### ISSUE TITLE
4.2.1 / Adding primary server throwing error

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#313]
- All CentOS 7. 
- Was trying to add first server, ClusterManager throwing below error: 

![Capture](https://user-images.githubusercontent.com/7156097/95022981-0cf52c80-0640-11eb-8bcc-bb04e82d5b2f.PNG)

- clustermanager.log saying: 

```
2020-10-04 17:46:16,400 - zico@local - INFO - [2020-Oct-04 17:46] 127.0.0.1 POST http /configuration/?next=%2Fserver%2F 302 FOUND
2020-10-04 17:46:16,744 - zico@local - INFO - [2020-Oct-04 17:46] 127.0.0.1 GET http /server/? 200 OK
2020-10-04 17:46:17,363 - zico@local - INFO - [2020-Oct-04 17:46] 127.0.0.1 GET http /static/css/bootstrap.min.css? 304 NOT MODIFIED
2020-10-04 17:46:17,370 - zico@local - INFO - [2020-Oct-04 17:46] 127.0.0.1 GET http /static/css/animate.css? 304 NOT MODIFIED
2020-10-04 17:46:17,376 - zico@local - INFO - [2020-Oct-04 17:46] 127.0.0.1 GET http /static/css/skin-blue.min.css? 304 NOT MODIFIED
2020-10-04 17:46:17,388 - zico@local - INFO - [2020-Oct-04 17:46] 127.0.0.1 GET http /static/css/AdminLTE.min.css? 304 NOT MODIFIED
2020-10-04 17:46:17,389 - zico@local - INFO - [2020-Oct-04 17:46] 127.0.0.1 GET http /static/css/app.css? 304 NOT MODIFIED
2020-10-04 17:46:40,193 - zico@local - DEBUG - RemoteClient created for host: ip-172-31-40-21.us-west-2.compute.internal
2020-10-04 17:46:40,193 - zico@local - DEBUG - Trying to connect to remote server ip-172-31-40-21.us-west-2.compute.internal:22
2020-10-04 17:46:40,229 - SYS - INFO - Connected (version 2.0, client OpenSSH_7.4)
2020-10-04 17:46:40,317 - SYS - INFO - Authentication (publickey) successful!
2020-10-04 17:46:40,629 - zico@local - INFO - [chan 0] Opened sftp connection (server version 3)
2020-10-04 17:46:40,632 - zico@local - DEBUG - INSERT[Server]: {"gluu_server": "None", "filebeat": "None", "monitoring": "None", "ldap_password": "Jun8azar!", "ip": "172.31.40.21", "hostname": "ip-172-31-40-21.us-west-2.compute.internal", "redis": "None", "cache_method": "None", "mmr": "False", "ssh_port": "22", "stunnel": "None", "components": "None", "os": "None", "id": "1", "primary_server": "True"}
2020-10-04 17:46:40,772 - zico@local - INFO - [2020-Oct-04 17:46] 127.0.0.1 POST http /server/? 302 FOUND
2020-10-04 17:46:41,158 - zico@local - DEBUG - RemoteClient created for host: 172.31.40.21
2020-10-04 17:46:41,158 - zico@local - DEBUG - Trying to connect to remote server 172.31.40.21:22
2020-10-04 17:46:41,170 - SYS - INFO - Connected (version 2.0, client OpenSSH_7.4)
2020-10-04 17:46:41,242 - SYS - INFO - Authentication (publickey) successful!
2020-10-04 17:46:41,529 - zico@local - INFO - [chan 0] Opened sftp connection (server version 3)
2020-10-04 17:46:41,530 - zico@local - ERROR - [2020-Oct-04 17:46] 127.0.0.1 GET http /? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/opt/clustermgr/clustermgr/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/clustermgr/clustermgr/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/clustermgr/clustermgr/clustermgr/views/index.py", line 110, in home
    services = get_enabled_services()
  File "/opt/clustermgr/clustermgr/clustermgr/core/utils.py", line 52, in get_enabled_services
    if as_boolean(prop[n]):
KeyError: 'installScimServer'

2020-10-04 17:46:41,534 - zico@local - INFO - [2020-Oct-04 17:46] 127.0.0.1 GET http /? 200 OK
[root@ip-172-31-0-43 logs]#
```

**Comment by mbaser** [comment]
This was fixed before by commit https://github.com/GluuFederation/cluster-mgr/commit/c88142326440a9e6458c72a33acc9c57aff44abc
