### ISSUE TITLE
Unable to install 2nd node if we use seed node ( Gluu Server ) to build cluster

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#325]
Environment: Ubuntu 20
CM version: 4.4-05

I was trying to build a Gluu 4.4.1 cluster from my existing single node Gluu Server. 
Second node installation is failing with below error: 

```
[2022-09-13 05:29:06,533: ERROR/ForkPoolWorker-1] Task clustermgr.tasks.server.task_install_gluu_server[9dcafd1c-36ff-490d-b1ec-1d9ec4299aa5] raised unexpected: Exception('Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/dist-packages/clustermgr/tasks/server.py", line 213, in task_install_gluu_server\n    install_gluu_server(task_id, server_id)\n  File "/usr/local/lib/python3.8/dist-packages/clustermgr/tasks/server.py", line 828, in install_gluu_server\n    if not ldapc.connect():\n  File "/usr/local/lib/python3.8/dist-packages/clustermgr/core/ldap_functions.py", line 59, in connect\n    return self.conn.bind()\n  File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 589, in bind\n    self.open(read_server_info=False)\n  File "/usr/local/lib/python3.8/dist-packages/ldap3/strategy/sync.py", line 57, in open\n    BaseStrategy.open(self, reset_usage, read_server_info)\n  File "/usr/local/lib/python3.8/dist-packages/ldap3/strategy/base.py", line 146, in open\n    raise exception_history[0][0]\nldap3.core.exceptions.LDAPSocketOpenError: socket connection error while opening: [Errno 111] Connection refused\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/clustermgr/tasks/server.py", line 213, in task_install_gluu_server
    install_gluu_server(task_id, server_id)
  File "/usr/local/lib/python3.8/dist-packages/clustermgr/tasks/server.py", line 828, in install_gluu_server
    if not ldapc.connect():
  File "/usr/local/lib/python3.8/dist-packages/clustermgr/core/ldap_functions.py", line 59, in connect
    return self.conn.bind()
  File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 589, in bind
    self.open(read_server_info=False)
  File "/usr/local/lib/python3.8/dist-packages/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/local/lib/python3.8/dist-packages/ldap3/strategy/base.py", line 146, in open
    raise exception_history[0][0]
ldap3.core.exceptions.LDAPSocketOpenError: socket connection error while opening: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/clustermgr/application.py", line 25, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/clustermgr/tasks/server.py", line 215, in task_install_gluu_server
    raise Exception(traceback.format_exc())
Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/clustermgr/tasks/server.py", line 213, in task_install_gluu_server
    install_gluu_server(task_id, server_id)
  File "/usr/local/lib/python3.8/dist-packages/clustermgr/tasks/server.py", line 828, in install_gluu_server
    if not ldapc.connect():
  File "/usr/local/lib/python3.8/dist-packages/clustermgr/core/ldap_functions.py", line 59, in connect
    return self.conn.bind()
  File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 589, in bind
    self.open(read_server_info=False)
  File "/usr/local/lib/python3.8/dist-packages/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/local/lib/python3.8/dist-packages/ldap3/strategy/base.py", line 146, in open
    raise exception_history[0][0]
ldap3.core.exceptions.LDAPSocketOpenError: socket connection error while opening: [Errno 111] Connection refused

```

**Comment by mzico** [comment]
Issue fixed!
