### ISSUE TITLE
Trying to change replication password, throwing IndexError 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#327]
![Peek 2022-10-03 23-59](https://user-images.githubusercontent.com/7156097/193646702-ef67cdb2-4a16-4afd-ae2f-8669d129e363.gif)

Error: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/clustermgr/views/index.py", line 191, in app_configuration
    cmd = ('/opt/opendj/bin/ldappasswordmodify --bindDN '
IndexError: Replacement index 0 out of range for positional args tuple
```

**Comment by devrimyatar** [comment]
Closed by https://github.com/GluuFederation/cluster-mgr/commit/22981ec21233e934dd085e78bdae1ceae8732182
