### ISSUE TITLE
CM installation failing in RHEL8

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#330]
After successful install, when I am going to start cluster manager, this is what appearing... 

```
[root@rhel8zico .ssh]# clustermgr4-cli start
Creating clustermgr data directory
Upgrading Database
Traceback (most recent call last):
  File "/usr/local/bin/clusterapp.py", line 162, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 445, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/cli.py", line 149, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/clustermgr/migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.6/site-packages/clustermgr/migrations/env.py", line 77, in run_migrations_online
    **current_app.extensions['migrate'].configure_args)
TypeError: configure() got multiple values for keyword argument 'render_as_batch'
Starting Celery Worker
celery multi v5.1.2 (sun-harmonics)
> Starting nodes...
	> worker@rhel8zico.gluu.info_cm: OK
Starting Celery Beat
Starting Gunicorn Web Server
[root@rhel8zico .ssh]# 
```
![Screenshot from 2022-11-15 01-01-44](https://user-images.githubusercontent.com/7156097/201745771-394d4b9c-7059-4cb0-ba50-5c249dfd3fb8.png)

**Comment by devrimyatar** [comment]
Fixed

**Comment by mzico** [comment]
It's fixed. Confirmed.
