### ISSUE TITLE
Failed to restart nutcracker in proxy server

### ISSUE THREAD

**Issue by iromli** [GluuFederation/cluster-mgr#95]
The issue occurs in `stable` branch.

![screenshot from 2017-11-19 22 49 03](https://user-images.githubusercontent.com/231601/32992371-607dc830-cd7c-11e7-859f-ab61d8166412.png)

As suggested by the output shown above, I traced the issue using `journalctl -xe` and searched for `nutcracker`.

```
-- Unit nutcracker.service has begun starting up.
Nov 19 15:48:37 cm nutcracker[22356]: nutcracker: configuration file '/etc/nutcracker/nutcracker.yml' syntax is invalid
Nov 19 15:48:37 cm systemd[1]: nutcracker.service: Control process exited, code=exited status=1
Nov 19 15:48:37 cm systemd[1]: Failed to start nutcracker - High performance proxy server for memcached/redis.
-- Subject: Unit nutcracker.service has failed
```
The problem was in `/etc/nutcracker/nutcracker.yml`, but I found that the file was empty. Not sure if `clustermgr` really render the template or not.

```
root@cm:~# cat /etc/nutcracker/nutcracker.yml 
root@cm:~# 
```

Also, from `celery` log, I found this error log:

```
[2017-11-19 22:44:33,601: ERROR/ForkPoolWorker-4] Task clustermgr.tasks.cache.configure_cache_cluster[926675a4-ef2a-4ca1-b331-4a6727caca03] raised unex
pected: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/home/iromli/.virtualenv/cluster-mgr/lib/python2.7/site-packages/celery-4.1.0-py2.7.egg/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/work/gluu/cluster-mgr/clustermgr/application.py", line 19, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/home/iromli/.virtualenv/cluster-mgr/lib/python2.7/site-packages/celery-4.1.0-py2.7.egg/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/work/gluu/cluster-mgr/clustermgr/tasks/cache.py", line 304, in configure_cache_cluster
    return setup_proxied(self.request.id)
  File "/opt/work/gluu/cluster-mgr/clustermgr/tasks/cache.py", line 516, in setup_proxied
    __update_LDAP_cache_method(tid, server, 'localhost:7000', 'STANDALONE')
  File "/opt/work/gluu/cluster-mgr/clustermgr/tasks/cache.py", line 476, in __update_LDAP_cache_method
    entry = dbm.get_appliance_attributes('oxCacheConfiguration')
  File "/opt/work/gluu/cluster-mgr/clustermgr/core/ldap_functions.py", line 726, in get_appliance_attributes
    return self.conn.entries[0]
IndexError: list index out of range
```

Again, I'm not sure if `IndexError` exception is related to nutcracker service issue.

Can anyone confirm this?

**Comment by afroDC** [comment]
Did we get this resolved @iromli ? I feel like we did

**Comment by afroDC** [comment]
Function works fine
