### ISSUE TITLE
Clicking Fetch cache methods throws exception

### ISSUE THREAD

**Issue by iromli** [GluuFederation/cluster-mgr#96]
Clicking the "Fetch cache methods" as shown below:

![screenshot from 2017-11-19 23 03 35](https://user-images.githubusercontent.com/231601/32992520-409b6c3c-cd7e-11e7-96c5-98a2deaeb901.png)

throws error in `celery` log:

```
[2017-11-19 23:02:06,113: INFO/MainProcess] Received task: clustermgr.tasks.cache.get_cache_methods[91dc2613-2a4e-4cbe-8c44-301e2d6a6f5a]  
[2017-11-19 23:02:07,083: ERROR/ForkPoolWorker-2] Task clustermgr.tasks.cache.get_cache_methods[91dc2613-2a4e-4cbe-8c44-301e2d6a6f5a] raised unexpected: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/home/iromli/.virtualenv/cluster-mgr/lib/python2.7/site-packages/celery-4.1.0-py2.7.egg/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/work/gluu/cluster-mgr/clustermgr/application.py", line 19, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/home/iromli/.virtualenv/cluster-mgr/lib/python2.7/site-packages/celery-4.1.0-py2.7.egg/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/work/gluu/cluster-mgr/clustermgr/tasks/cache.py", line 780, in get_cache_methods
    entry = dbm.get_appliance_attributes('oxCacheConfiguration')
  File "/opt/work/gluu/cluster-mgr/clustermgr/core/ldap_functions.py", line 726, in get_appliance_attributes
    return self.conn.entries[0]
IndexError: list index out of range
```

**Comment by iromli** [comment]
It seems related to issue #95.

**Comment by afroDC** [comment]
This one seems like it was a bug that was resolved as well @iromli

**Comment by iromli** [comment]
Tested on `master` branch and the issue didn't appear. Closing ...
